export const siteConfig = {
  name: "Swarms AI - Enterprise Multi-Agent Framework",
  description:
    "Build, deploy, and scale autonomous AI agent swarms with unprecedented control and efficiency. The leading enterprise-grade framework for orchestrating multiple AI agents, featuring sequential workflows, parallel processing, and mixture architectures.",
  url: "https://swarms.ai",
  ogImage: "/backend.jpg", // Use backend.jpg for Open Graph and SEO
  logo: "/logo.svg", // Use logo.svg for logo and favicon
  seoBackground: "/backend.jpg", // Custom field for SEO background
  links: {
    github: "https://github.com/kyegomez/swarms",
    docs: "https://docs.swarms.world",
    marketplace: "https://swarms.world",
  },
  keywords: [
    "AI",
    "artificial intelligence",
    "multi-agent system",
    "agent framework",
    "AI orchestration",
    "enterprise AI",
    "machine learning",
    "autonomous agents",
    "AI swarms",
    "distributed AI",
    "AI automation",
    "AI tools",
    "AI development",
    "AI infrastructure",
    "sequential workflow",
    "parallel processing",
    "agent mixture",
    "swarm architecture",
    "AI optimization",
    "enterprise software",
    "open source AI",
    "AI platform",
    "AI marketplace",
    "AI deployment",
    "AI monitoring",
    "AI scaling",
    "AI production",
    "AI research",
    "AI templates",
    "AI examples",
    "AI documentation",
    "AI cloud",
    "AI Rust",
    "AI Python",
    "Swarms API",
    "Swarms Marketplace",
    "Swarms Rust",
    "Swarms Python",
    "Swarms Cloud",
    "Swarms Docs",
    "Swarms Open Source",
    "Swarms Agents",
    "Swarms Framework",
    "Swarms Infrastructure",
    "Swarms Platform",
    "Swarms Templates",
    "Swarms Examples",
    "Swarms Research",
    "Swarms Automation",
    "Swarms Monitoring",
    "Swarms Scaling",
    "Swarms Production",
    "Swarms Development",
    "Swarms Orchestration",
    "Swarms Collaboration",
    "Swarms Innovation",
    "Swarms Technology",
    "Swarms Solutions",
    "Swarms Products",
    "Swarms Community",
    "Swarms Support",
    "Swarms Documentation",
    "Swarms Tutorials",
    "Swarms Guides",
    "Swarms API Reference",
    "Swarms Cloud API",
    "Swarms Rust API",
    "Swarms Python API",
    "Swarms Marketplace API",
    "Swarms Cloud Platform",
    "Swarms Rust Platform",
    "Swarms Python Platform",
    "Swarms Marketplace Platform",
    "Swarms Cloud Infrastructure",
    "Swarms Rust Infrastructure",
    "Swarms Python Infrastructure",
    "Swarms Marketplace Infrastructure",
    "Swarms Cloud Solutions",
    "Swarms Rust Solutions",
    "Swarms Python Solutions",
    "Swarms Marketplace Solutions",
    "Swarms Cloud Products",
    "Swarms Rust Products",
    "Swarms Python Products",
    "Swarms Marketplace Products",
  ],
  company: {
    name: "Swarms AI",
    description: "Leading provider of enterprise-grade AI agent orchestration solutions",
    foundingDate: "2023",
    founders: [
      {
        name: "Kye Gomez",
        url: "https://github.com/kyegomez",
      },
    ],
    address: {
      addressCountry: "US",
    },
  },
}
